spring.application.name=locklens

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/locklens}
spring.datasource.username=${DB_USERNAME:locklens}
spring.datasource.password=${DB_PASSWORD:locklens}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always